# coding=utf-8

ESTADOS_BRASILEIROS_NOMES = (
    ('AC', u'Acre'),
    ('AL', u'Alagoas'),
    ('AP', u'Amapá'),
    ('AM', u'Amapá'),
    ('BA', u'Bahia'),
    ('CE', u'Ceará'),
    ('DF', u'Distrito Federal'),
    ('ES', u'Espírito Santo'),
    ('GO', u'Goiás'),
    ('MA', u'Maranhão'),
    ('MT', u'Mato Grosso'),
    ('MS', u'Mato Grosso do Sul'),
    ('MG', u'Minas Gerais'),
    ('PA', u'Pará'),
    ('PR', u'Paraná'),
    ('PE', u'Pernambuco'),
    ('PI', u'Piauí'),
    ('RJ', u'Rio de Janeiro'),
    ('RN', u'Rio Grande do Norte'),
    ('RS', u'Rio Grande do Sul'),
    ('RO', u'Rondônia'),
    ('RR', u'Roraima'),
    ('SC', u'Santa Catarina'),
    ('SP', u'Sao Paulo'),
    ('SE', u'Sergipe'),
    ('TO', u'Tocantins'),
)
ESTADOS_BRASILEIROS_SIGLAS = (
    ('AC', 'AC'),
    ('AL', 'AL'),
    ('AP', 'AP'),
    ('AM', 'AM'),
    ('BA', 'BA'),
    ('CE', 'CE'),
    ('DF', 'DF'),
    ('ES', 'ES'),
    ('GO', 'GO'),
    ('MA', 'MA'),
    ('MT', 'MT'),
    ('MS', 'MS'),
    ('MG', 'MG'),
    ('PA', 'PA'),
    ('PR', 'PR'),
    ('PE', 'PE'),
    ('PI', 'PI'),
    ('RJ', 'RJ'),
    ('RN', 'RN'),
    ('RS', 'RS'),
    ('RO', 'RO'),
    ('RR', 'RR'),
    ('SC', 'SC'),
    ('SP', 'SP'),
    ('SE', 'SE'),
    ('TO', 'TO'),
)

DDDS = [
    ('11', '(11) São Paulo'),
    ('12', '(12) São Paulo'),
    ('13', '(13) São Paulo'),
    ('14', '(14) São Paulo'),
    ('15', '(15) São Paulo'),
    ('16', '(16) São Paulo'),
    ('17', '(17) São Paulo'),
    ('18', '(18) São Paulo'),
    ('19', '(19) São Paulo'),
    ('21', '(21) Rio de Janeiro'),
    ('22', '(22) Rio de Janeiro'),
    ('24', '(24) Rio de Janeiro'),
    ('27', '(27) Espírito Santo'),
    ('28', '(28) Espírito Santo'),
    ('31', '(31) Minas Gerais'),
    ('32', '(32) Minas Gerais'),
    ('33', '(33) Minas Gerais'),
    ('34', '(34) Minas Gerais'),
    ('35', '(35) Minas Gerais'),
    ('37', '(37) Minas Gerais'),
    ('38', '(38) Minas Gerais'),
    ('41', '(41) Paraná'),
    ('42', '(42) Paraná'),
    ('43', '(43) Paraná'),
    ('44', '(44) Paraná'),
    ('45', '(45) Paraná'),
    ('46', '(46) Paraná'),
    ('47', '(47) Santa Catarina'),
    ('48', '(48) Santa Catarina'),
    ('49', '(49) Santa Catarina'),
    ('51', '(51) Rio Grande do Sul'),
    ('53', '(53) Rio Grande do Sul'),
    ('54', '(54) Rio Grande do Sul'),
    ('55', '(55) Rio Grande do Sul'),
    ('61', '(61) Distrito Federal e Goiás'),
    ('62', '(62) Goiás'),
    ('63', '(63) Tocantins'),
    ('64', '(64) Goiás'),
    ('65', '(65) Mato Grosso'),
    ('66', '(66) Mato Grosso'),
    ('67', '(67) Mato Grosso do Sul'),
    ('68', '(68) Acre'),
    ('69', '(69) Rondônia'),
    ('71', '(71) Bahia'),
    ('73', '(73) Bahia'),
    ('74', '(74) Bahia'),
    ('75', '(75) Bahia'),
    ('77', '(77) Bahia'),
    ('79', '(79) Sergipe'),
    ('81', '(81) Pernambuco'),
    ('82', '(82) Alagoas'),
    ('83', '(83) Paraíba'),
    ('84', '(84) Rio Grande do Norte'),
    ('85', '(85) Ceará'),
    ('86', '(86) Piauí'),
    ('87', '(87) Pernambuco'),
    ('88', '(88) Ceará'),
    ('89', '(89) Piauí'),
    ('91', '(91) Pará'),
    ('92', '(92) Amazonas'),
    ('93', '(93) Pará'),
    ('94', '(94) Pará'),
    ('95', '(95) Roraima'),
    ('96', '(96) Amapá'),
    ('97', '(97) Amazonas'),
    ('98', '(98) Maranhão'),
    ('99', '(99) Maranhão')
]